# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: aws-iam-service-linked-roles
  description: This component is responsible for provisioning IAM Service-Linked Roles
  homepage: https://cloudposse.com/accelerate
  topics: terraform, terraform-component




